version: '3'
services:
  redis:
    image: redis:5.0-alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
  flask:
    build: flask
    ports:
      - 5000:5000
    volumes:
      - ./flask:/app
    depends_on:
      - redis
  server:
    build: server
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./server:/app
    depends_on:
      - redis
  web:
    build: web
    ports:
     - 3000:3000
     - 9222:9222
    volumes:
      - ./web/src:/app/src
    depends_on:
      - flask
      - server