version: '3'

volumes:
  mysql:

services:
  database:
    image: mongo:4.0
    environment:
      - MONGO_INITDB_DATABASE=testing
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  prisma:
    build: prisma
    ports:
      - 4466:4466
    volumes:
      - ./prisma:/app
  flask:
    build: flask
    ports:
      - 5000:5000
    volumes:
      - ./flask:/app
  server:
    build: server
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./server:/app
  web:
    build: web
    ports:
     - 3000:3000
     - 9222:9222
    volumes:
      - ./web/src:/app/src