version: '3'
volumes:
  mysql:
services:
  prisma:
    image: prismagraphql/prisma:1.18
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
            rawAccess: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  database:
    image: mongo:4.0
    environment:
      - MONGO_INITDB_DATABASE=testing
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  flask:
    build: flask
    ports:
      - 5000:5000
    volumes:
      - ./flask:/app
  server:
    build: server
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./server:/app
  web:
    build: web
    ports:
     - 3000:3000
     - 9222:9222
    volumes:
      - ./web/src:/app/src